In [9]:
import numpy as np

In [2]:
edgeList = [[0,2], [1,3], [2,3], [2,4], [3,5], [4,5]]

In [3]:
edgeList

[[0, 2], [1, 3], [2, 3], [2, 4], [3, 5], [4, 5]]

In [14]:
adjMatrix = np.array([[0,0,1,0,0,0],[0,0,0,1,0,0],[0,0,0,1,1,0],[0,0,0,0,0,1],[0,0,0,0,0,1]])

In [15]:
adjMatrix

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1]])

In [16]:
adjList = [[2],[3],[3,4],[5],[5],[]]

In [13]:
adjMatrix

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]])

In [10]:
np.empty((2, 3))

array([[4.03659063e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
# adjMatrix = numpy.zeros(shape=(6,6))
# edgeList = [ [0,2], [1,3], [2,3], [2,4], [3,5], [4,5] ]
# for nodo in edgeList:
#     x = nodo[0]
#     y = nodo[1]
#     adjMatrix[x,y] = 1

In [17]:
adjList

[[2], [3], [3, 4], [5], [5], []]